export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const careerPageStyle = {
  boxSizing: "border-box",
  width: "60%",
  minWidth: "50rem",
};

export default function CareerLayout({ children }) {
  return <div style={careerPageStyle}>{children}</div>;
}
