import { Providers } from "@/redux/provider";
import Topbar from "@/components/shared/Topbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Bottombar from "@/components/shared/Bottombar";
import StyledComponentsRegistry from "../lib/registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        {/* <Providers> */}
        <StyledComponentsRegistry>
          <Topbar />
          <main className="main-container">{children}</main>
          <Bottombar />
        </StyledComponentsRegistry>
        {/* </Providers> */}
      </body>
    </html>
  );
}
