import Topbar from "@/components/shared/Topbar";
// import "../../globals.css";
import LeftSidebar from "@/components/shared/LeftSidebar";
import RightSidebar from "@/components/shared/RightSidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ProjectContainerStyle = {
  boxSizing: "border-box",
  width: "40%",
  minWidth: "50rem",
};

export default function ProjectLayout({ children }) {
  return (
    <>
      <LeftSidebar postsDir={"./posts/project"} />
      <div style={ProjectContainerStyle}>{children}</div>
      <RightSidebar />
    </>
  );
}
