// import "../../../globals.css";
// "use client";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BlogPostLayout({ children }) {
  return <div className="blogpost-container">{children}</div>;
}
